//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateAPIRefHelp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CreateAPIRefHelp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=SDKAODOC.esri.com;database=EnterpriseSDK;Integrated Security=True;Connect Timeout=15;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False.
        /// </summary>
        internal static string _DbConnectionStr {
            get {
                return ResourceManager.GetString("_DbConnectionStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### $ConstructorName$ Constructor
        ///
        ///$ConstructorDescription$
        ///
        ///$ConstructorSyntax$
        ///
        ///$ConstructorParameters$
        ///
        ///
        ///.
        /// </summary>
        internal static string ConstructorDetailMdTemplate {
            get {
                return ResourceManager.GetString("ConstructorDetailMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Constructors
        ///
        ///|Constructor | Description |
        ///|------|------|
        ///$ConstructorList$
        ///
        ///$ConstructorDetails$
        ///.
        /// </summary>
        internal static string ConstructorMdTemplate {
            get {
                return ResourceManager.GetString("ConstructorMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///|Name | Value | Description |
        ///|------|------|------|
        ///.
        /// </summary>
        internal static string EnumHeaderMdTemplate {
            get {
                return ResourceManager.GetString("EnumHeaderMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Fields
        ///
        ///|Field | Field value | Description |
        ///|------|------|------|
        ///|$FieldName$ | $FieldType$ | $FieldDescription$  |
        ///.
        /// </summary>
        internal static string FieldsMdTemplate {
            get {
                return ResourceManager.GetString("FieldsMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #### Inheritance Hierarchy
        ///
        ///```cs
        ///$Inheritance$
        ///```
        ///.
        /// </summary>
        internal static string InheritanceMdTemplate {
            get {
                return ResourceManager.GetString("InheritanceMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### $MemberName$
        ///  
        ///$MemberDescription$
        ///
        ///#### Syntax
        ///
        ///```cs
        ///$SyntaxCS$
        ///```
        ///
        ///$MemberRemarks$
        ///$MemberSamples$
        ///.
        /// </summary>
        internal static string MemberDetailMdTemplate {
            get {
                return ResourceManager.GetString("MemberDetailMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |Property | Property value | Description |
        ///|------|------|------|.
        /// </summary>
        internal static string MemberHeaderMdTemplate {
            get {
                return ResourceManager.GetString("MemberHeaderMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Members
        ///
        ///|Type|Member Name|Description|
        ///|------|------|------|
        ///$MemberList$
        ///
        ///$MemberDetails$
        ///
        ///.
        /// </summary>
        internal static string MemberMdTemplate {
            get {
                return ResourceManager.GetString("MemberMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Remarks$.
        /// </summary>
        internal static string MemberRemarksMdTemplate {
            get {
                return ResourceManager.GetString("MemberRemarksMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///|Name | Description |
        ///|------|------|
        ///.
        /// </summary>
        internal static string MethodHeader2MdTemplate {
            get {
                return ResourceManager.GetString("MethodHeader2MdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///| |Name | Description |
        ///|------|------|------|
        ///.
        /// </summary>
        internal static string MethodHeader3MdTemplate {
            get {
                return ResourceManager.GetString("MethodHeader3MdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///### $MethodName$ Method
        ///
        ///$MethodDescription$
        ///
        ///$MethodSampleCode$
        ///``` c#
        ///public static IEnumerable&lt;IFeature&gt; Search(this IFeatureClass fc)
        ///```
        ///
        ///$MethodParameters$
        ///
        ///$MethodRemarks$
        ///
        ///**Usage:**
        ///$MethodUsage$
        ///``` c#
        ///    IEnumerable&lt;IFeature&gt; features = featureClass.Search();
        ///    foreach (IFeature f in features)
        ///    {
        ///        // perform your operation
        ///    }
        ///```.
        /// </summary>
        internal static string MethodMdTemplate {
            get {
                return ResourceManager.GetString("MethodMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |Parameter | Description |
        ///|-----|------|
        ///
        ///.
        /// </summary>
        internal static string MethodParameterMdTemplate {
            get {
                return ResourceManager.GetString("MethodParameterMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Methods
        ///
        ///|Name | Description |
        ///|------|------|
        ///| $MethodName$|$MethodDescription$|
        ///
        ///[RestOperation.ToJsonObject()](#restoperationtojsonobject-method) 
        ///
        ///### $MethodName$ Method
        ///
        ///Converts the RestOperation to a JsonObject instance. 
        ///
        ///```c#
        ///$MethodSampleCode$
        ///```.
        /// </summary>
        internal static string MethodsMdTemplate {
            get {
                return ResourceManager.GetString("MethodsMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # $Class$ Class
        ///
        ///$ClassDescription$
        ///
        ///$ClassSyntax$
        ///
        ///$ClassRemarks$ 
        ///
        ///$ClassInheritance$
        ///
        ///$Constructors$
        ///
        ///$Members$
        ///
        ///$Methods$
        ///
        ///$Fields$
        ///
        ///$Properties$
        ///
        ///
        ///.
        /// </summary>
        internal static string PageClassMdTemplate {
            get {
                return ResourceManager.GetString("PageClassMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///# $coclass$ Coclass
        ///
        ///# $coclass$
        ///
        ///$coclassRemarks$
        ///## Interfaces implemented by $coclass$
        ///
        ///$InterfaceDescriptions$
        ///
        ///## Members
        ///$Members$
        ///
        ///$MembersDetails$
        ///.
        /// </summary>
        internal static string PageCoClassMdTemplate {
            get {
                return ResourceManager.GetString("PageCoClassMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # $namespace$ Namespace Contents
        ///## $namespaceRemarks$
        ///
        ///## Interfaces
        ///    $interfaces$
        ///
        ///## Coclasses
        ///    $Classes$
        ///
        ///## Enumerations
        ///    $Enumerations$
        ///.
        /// </summary>
        internal static string PageComNamespaceMdTemplate {
            get {
                return ResourceManager.GetString("PageComNamespaceMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # $Enum$ Constants
        ///
        ///$EnumDescription$
        ///
        ///$EnumRemarks$
        ///
        ///$Constants$
        ///.
        /// </summary>
        internal static string PageEnumMdTemplate {
            get {
                return ResourceManager.GetString("PageEnumMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # $Interface$ Interface
        ///
        ///$InterfaceDescription$
        ///
        ///$InterfaceRemarks$
        ///---
        ///$Members$
        ///---
        ///$MembersDetails$
        ///
        ///$MemberRemarks$
        ///
        ///$MemberSamples$.
        /// </summary>
        internal static string PageInterfaceMdTemplate {
            get {
                return ResourceManager.GetString("PageInterfaceMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # $namespace$ Namespace Contents
        ///## $namespaceRemarks$
        ///
        ///## Interfaces
        ///    $interfaces$
        ///
        ///## Classes
        ///    $Classes$
        ///
        ///## Enumerations
        ///    $Enumerations$
        ///.
        /// </summary>
        internal static string PageNamespaceMdTemplate {
            get {
                return ResourceManager.GetString("PageNamespaceMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## Properties
        ///
        ///|Property | Property value | Description |
        ///|------|------|------|
        ///.
        /// </summary>
        internal static string PropertiesMdTemplate {
            get {
                return ResourceManager.GetString("PropertiesMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Remarks$.
        /// </summary>
        internal static string RemarksMdTemplate {
            get {
                return ResourceManager.GetString("RemarksMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # RestOperation Class
        ///
        ///A class that represents a REST operation. 
        ///
        ///
        ///---
        ///## Constructors
        ///|Name | Description |
        ///|------|
        ///|[RestOperation(String, String[], String[], OperationHandler)](#restoperationstring-string-string-operationhandler-constructor)| Creates a new RestOperation instance.  |
        ///| [RestOperation(String, String[], String[], OperationHandler, Boolean)](#restoperationstring-string-string-operationhandler-boolean-constructor) | Creates a new RestOperation instance. | 
        ///| [RestOperation(String [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RestOperationMdTemplate {
            get {
                return ResourceManager.GetString("RestOperationMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre&gt;
        ///&lt;code class=&quot;$language$&quot;&gt;
        ///$sampleCode$
        ///&lt;/code&gt;
        ///&lt;/pre&gt;.
        /// </summary>
        internal static string SampleMdTemplate {
            get {
                return ResourceManager.GetString("SampleMdTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #### Syntax
        ///
        ///```cs
        ///$SyntaxCS$
        ///```
        ///.
        /// </summary>
        internal static string SyntaxMdTemplate {
            get {
                return ResourceManager.GetString("SyntaxMdTemplate", resourceCulture);
            }
        }
    }
}
