### YamlMime:ManagedReference
items:
- uid: ESRI.ArcGIS.esriSystem.IExtensionConfig
  commentId: T:ESRI.ArcGIS.esriSystem.IExtensionConfig
  id: IExtensionConfig
  parent: ESRI.ArcGIS.esriSystem
  children:
  - ESRI.ArcGIS.esriSystem.IExtensionConfig.Description
  - ESRI.ArcGIS.esriSystem.IExtensionConfig.ProductName
  - ESRI.ArcGIS.esriSystem.IExtensionConfig.State
  langs:
  - csharp
  - vb
  name: IExtensionConfig
  nameWithType: IExtensionConfig
  fullName: ESRI.ArcGIS.esriSystem.IExtensionConfig
  type: Interface
  assemblies:
  - ESRI.Server.System
  namespace: ESRI.ArcGIS.esriSystem
  summary: Provides access to members that describe an extension.
  example: []
  syntax:
    content: >-
      [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]

      [Guid("12A4C258-CC9D-4CA7-9F29-79DED88DD45F")]

      public interface IExtensionConfig
    content.vb: >-
      <InterfaceType(ComInterfaceType.InterfaceIsIUnknown)>

      <Guid("12A4C258-CC9D-4CA7-9F29-79DED88DD45F")>

      Public Interface IExtensionConfig
  derivedClasses:
  - ESRI.ArcGIS.Geodatabase.DddServerEnvironmentClass
  attributes:
  - type: System.Runtime.InteropServices.InterfaceTypeAttribute
    ctor: System.Runtime.InteropServices.InterfaceTypeAttribute.#ctor(System.Runtime.InteropServices.ComInterfaceType)
    arguments:
    - type: System.Runtime.InteropServices.ComInterfaceType
      value: 1
  - type: System.Runtime.InteropServices.GuidAttribute
    ctor: System.Runtime.InteropServices.GuidAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: 12A4C258-CC9D-4CA7-9F29-79DED88DD45F
- uid: ESRI.ArcGIS.esriSystem.IExtensionConfig.ProductName
  commentId: P:ESRI.ArcGIS.esriSystem.IExtensionConfig.ProductName
  id: ProductName
  parent: ESRI.ArcGIS.esriSystem.IExtensionConfig
  langs:
  - csharp
  - vb
  name: ProductName
  nameWithType: IExtensionConfig.ProductName
  fullName: ESRI.ArcGIS.esriSystem.IExtensionConfig.ProductName
  type: Property
  assemblies:
  - ESRI.Server.System
  namespace: ESRI.ArcGIS.esriSystem
  summary: Name of the extension.
  example:
  - >-
    <codeTitle>Sample Snippet</codeTitle>

    <pre><code class="lang-csharp"></code></pre>
  syntax:
    content: string ProductName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property ProductName As String
  overload: ESRI.ArcGIS.esriSystem.IExtensionConfig.ProductName*
- uid: ESRI.ArcGIS.esriSystem.IExtensionConfig.Description
  commentId: P:ESRI.ArcGIS.esriSystem.IExtensionConfig.Description
  id: Description
  parent: ESRI.ArcGIS.esriSystem.IExtensionConfig
  langs:
  - csharp
  - vb
  name: Description
  nameWithType: IExtensionConfig.Description
  fullName: ESRI.ArcGIS.esriSystem.IExtensionConfig.Description
  type: Property
  assemblies:
  - ESRI.Server.System
  namespace: ESRI.ArcGIS.esriSystem
  summary: Detailed description of the extension.
  example:
  - >-
    <codeTitle>Sample Snippet</codeTitle>

    <pre><code class="lang-csharp"></code></pre>
  syntax:
    content: string Description { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property Description As String
  overload: ESRI.ArcGIS.esriSystem.IExtensionConfig.Description*
- uid: ESRI.ArcGIS.esriSystem.IExtensionConfig.State
  commentId: P:ESRI.ArcGIS.esriSystem.IExtensionConfig.State
  id: State
  parent: ESRI.ArcGIS.esriSystem.IExtensionConfig
  langs:
  - csharp
  - vb
  name: State
  nameWithType: IExtensionConfig.State
  fullName: ESRI.ArcGIS.esriSystem.IExtensionConfig.State
  type: Property
  assemblies:
  - ESRI.Server.System
  namespace: ESRI.ArcGIS.esriSystem
  summary: The state of the extension.
  example:
  - >-
    <codeTitle>Sample Snippet</codeTitle>

    <pre><code class="lang-csharp"></code></pre>
  syntax:
    content: esriExtensionState State { get; set; }
    parameters: []
    return:
      type: ESRI.ArcGIS.esriSystem.esriExtensionState
    content.vb: Property State As esriExtensionState
  overload: ESRI.ArcGIS.esriSystem.IExtensionConfig.State*
references:
- uid: ESRI.ArcGIS.esriSystem
  commentId: N:ESRI.ArcGIS.esriSystem
  isExternal: true
  href: ESRI.html
  name: ESRI.ArcGIS.esriSystem
  nameWithType: ESRI.ArcGIS.esriSystem
  fullName: ESRI.ArcGIS.esriSystem
  spec.csharp:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.esriSystem
    name: esriSystem
    isExternal: true
    href: ESRI.ArcGIS.esriSystem.html
  spec.vb:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.esriSystem
    name: esriSystem
    isExternal: true
    href: ESRI.ArcGIS.esriSystem.html
- uid: ESRI.ArcGIS.esriSystem.IExtensionConfig.ProductName*
  commentId: Overload:ESRI.ArcGIS.esriSystem.IExtensionConfig.ProductName
  isExternal: true
  href: ESRI.ArcGIS.esriSystem.IExtensionConfig.html#ESRI_ArcGIS_esriSystem_IExtensionConfig_ProductName
  name: ProductName
  nameWithType: IExtensionConfig.ProductName
  fullName: ESRI.ArcGIS.esriSystem.IExtensionConfig.ProductName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ESRI.ArcGIS.esriSystem.IExtensionConfig.Description*
  commentId: Overload:ESRI.ArcGIS.esriSystem.IExtensionConfig.Description
  isExternal: true
  href: ESRI.ArcGIS.esriSystem.IExtensionConfig.html#ESRI_ArcGIS_esriSystem_IExtensionConfig_Description
  name: Description
  nameWithType: IExtensionConfig.Description
  fullName: ESRI.ArcGIS.esriSystem.IExtensionConfig.Description
- uid: ESRI.ArcGIS.esriSystem.IExtensionConfig.State*
  commentId: Overload:ESRI.ArcGIS.esriSystem.IExtensionConfig.State
  isExternal: true
  href: ESRI.ArcGIS.esriSystem.IExtensionConfig.html#ESRI_ArcGIS_esriSystem_IExtensionConfig_State
  name: State
  nameWithType: IExtensionConfig.State
  fullName: ESRI.ArcGIS.esriSystem.IExtensionConfig.State
- uid: ESRI.ArcGIS.esriSystem.esriExtensionState
  commentId: T:ESRI.ArcGIS.esriSystem.esriExtensionState
  parent: ESRI.ArcGIS.esriSystem
  isExternal: true
  href: ESRI.ArcGIS.esriSystem.esriExtensionState.html
  name: esriExtensionState
  nameWithType: esriExtensionState
  fullName: ESRI.ArcGIS.esriSystem.esriExtensionState
