### YamlMime:ManagedReference
items:
- uid: ESRI.ArcGIS.Geometry.GeometryEnvironment
  commentId: T:ESRI.ArcGIS.Geometry.GeometryEnvironment
  id: GeometryEnvironment
  parent: ESRI.ArcGIS.Geometry
  children: []
  langs:
  - csharp
  - vb
  name: GeometryEnvironment
  nameWithType: GeometryEnvironment
  fullName: ESRI.ArcGIS.Geometry.GeometryEnvironment
  type: Interface
  assemblies:
  - ESRI.Server.Geometry
  namespace: ESRI.ArcGIS.Geometry
  summary: Provides a way of creating geometries from different inputs and setting/getting global variables for controlling behavior of geometry methods.
  example: []
  syntax:
    content: >-
      [Guid("DF0B3D60-548F-101B-8E65-08002B2BD119")]

      public interface GeometryEnvironment : ISupportErrorInfo
    content.vb: >-
      <Guid("DF0B3D60-548F-101B-8E65-08002B2BD119")>

      Public Interface GeometryEnvironment Inherits ISupportErrorInfo
  derivedClasses:
  - ESRI.ArcGIS.Geometry.GeometryEnvironmentClass
  inheritedMembers:
  - ESRI.ArcGIS.esriSystem.ISupportErrorInfo.InterfaceSupportsErrorInfo(System.Guid@)
  attributes:
  - type: System.Runtime.InteropServices.GuidAttribute
    ctor: System.Runtime.InteropServices.GuidAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: DF0B3D60-548F-101B-8E65-08002B2BD119
references:
- uid: ESRI.ArcGIS.Geometry
  commentId: N:ESRI.ArcGIS.Geometry
  isExternal: true
  href: ESRI.html
  name: ESRI.ArcGIS.Geometry
  nameWithType: ESRI.ArcGIS.Geometry
  fullName: ESRI.ArcGIS.Geometry
  spec.csharp:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.Geometry
    name: Geometry
    isExternal: true
    href: ESRI.ArcGIS.Geometry.html
  spec.vb:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.Geometry
    name: Geometry
    isExternal: true
    href: ESRI.ArcGIS.Geometry.html
- uid: ESRI.ArcGIS.esriSystem.ISupportErrorInfo.InterfaceSupportsErrorInfo(System.Guid@)
  commentId: M:ESRI.ArcGIS.esriSystem.ISupportErrorInfo.InterfaceSupportsErrorInfo(System.Guid@)
  parent: ESRI.ArcGIS.esriSystem.ISupportErrorInfo
  isExternal: true
  href: ESRI.ArcGIS.esriSystem.ISupportErrorInfo.html#ESRI_ArcGIS_esriSystem_ISupportErrorInfo_InterfaceSupportsErrorInfo_System_Guid__
  name: InterfaceSupportsErrorInfo(ref Guid)
  nameWithType: ISupportErrorInfo.InterfaceSupportsErrorInfo(ref Guid)
  fullName: ESRI.ArcGIS.esriSystem.ISupportErrorInfo.InterfaceSupportsErrorInfo(ref System.Guid)
  nameWithType.vb: ISupportErrorInfo.InterfaceSupportsErrorInfo(Guid)
  fullName.vb: ESRI.ArcGIS.esriSystem.ISupportErrorInfo.InterfaceSupportsErrorInfo(System.Guid)
  name.vb: InterfaceSupportsErrorInfo(Guid)
  spec.csharp:
  - uid: ESRI.ArcGIS.esriSystem.ISupportErrorInfo.InterfaceSupportsErrorInfo(System.Guid@)
    name: InterfaceSupportsErrorInfo
    isExternal: true
    href: ESRI.ArcGIS.esriSystem.ISupportErrorInfo.html#ESRI_ArcGIS_esriSystem_ISupportErrorInfo_InterfaceSupportsErrorInfo_System_Guid__
  - name: (
  - name: ref
  - name: " "
  - uid: System.Guid
    name: Guid
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.guid
  - name: )
  spec.vb:
  - uid: ESRI.ArcGIS.esriSystem.ISupportErrorInfo.InterfaceSupportsErrorInfo(System.Guid@)
    name: InterfaceSupportsErrorInfo
    isExternal: true
    href: ESRI.ArcGIS.esriSystem.ISupportErrorInfo.html#ESRI_ArcGIS_esriSystem_ISupportErrorInfo_InterfaceSupportsErrorInfo_System_Guid__
  - name: (
  - uid: System.Guid
    name: Guid
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.guid
  - name: )
- uid: ESRI.ArcGIS.esriSystem.ISupportErrorInfo
  commentId: T:ESRI.ArcGIS.esriSystem.ISupportErrorInfo
  parent: ESRI.ArcGIS.esriSystem
  isExternal: true
  href: ESRI.ArcGIS.esriSystem.ISupportErrorInfo.html
  name: ISupportErrorInfo
  nameWithType: ISupportErrorInfo
  fullName: ESRI.ArcGIS.esriSystem.ISupportErrorInfo
- uid: ESRI.ArcGIS.esriSystem
  commentId: N:ESRI.ArcGIS.esriSystem
  isExternal: true
  href: ESRI.html
  name: ESRI.ArcGIS.esriSystem
  nameWithType: ESRI.ArcGIS.esriSystem
  fullName: ESRI.ArcGIS.esriSystem
  spec.csharp:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.esriSystem
    name: esriSystem
    isExternal: true
    href: ESRI.ArcGIS.esriSystem.html
  spec.vb:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.esriSystem
    name: esriSystem
    isExternal: true
    href: ESRI.ArcGIS.esriSystem.html
