### YamlMime:ManagedReference
items:
- uid: ESRI.ArcGIS.Server.esriConfigurationStatus
  commentId: T:ESRI.ArcGIS.Server.esriConfigurationStatus
  id: esriConfigurationStatus
  parent: ESRI.ArcGIS.Server
  children:
  - ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSDeleted
  - ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSPaused
  - ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSStarted
  - ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSStarting
  - ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSStopped
  - ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSStopping
  langs:
  - csharp
  - vb
  name: esriConfigurationStatus
  nameWithType: esriConfigurationStatus
  fullName: ESRI.ArcGIS.Server.esriConfigurationStatus
  type: Enum
  assemblies:
  - ESRI.Server.Server
  namespace: ESRI.ArcGIS.Server
  summary: Server object configuration status.
  example: []
  syntax:
    content: >-
      [Guid("7098BCE5-4172-469E-B689-4D7D0E25EE37")]

      public enum esriConfigurationStatus
    content.vb: >-
      <Guid("7098BCE5-4172-469E-B689-4D7D0E25EE37")>

      Public Enum esriConfigurationStatus
  attributes:
  - type: System.Runtime.InteropServices.GuidAttribute
    ctor: System.Runtime.InteropServices.GuidAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: 7098BCE5-4172-469E-B689-4D7D0E25EE37
- uid: ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSStarted
  commentId: F:ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSStarted
  id: esriCSStarted
  parent: ESRI.ArcGIS.Server.esriConfigurationStatus
  langs:
  - csharp
  - vb
  name: esriCSStarted
  nameWithType: esriConfigurationStatus.esriCSStarted
  fullName: ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSStarted
  type: Field
  assemblies:
  - ESRI.Server.Server
  namespace: ESRI.ArcGIS.Server
  summary: '0: The server object configuration is started.'
  example: []
  syntax:
    content: esriCSStarted = 0
    return:
      type: ESRI.ArcGIS.Server.esriConfigurationStatus
- uid: ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSPaused
  commentId: F:ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSPaused
  id: esriCSPaused
  parent: ESRI.ArcGIS.Server.esriConfigurationStatus
  langs:
  - csharp
  - vb
  name: esriCSPaused
  nameWithType: esriConfigurationStatus.esriCSPaused
  fullName: ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSPaused
  type: Field
  assemblies:
  - ESRI.Server.Server
  namespace: ESRI.ArcGIS.Server
  summary: '1: The server object configuration is paused.'
  example: []
  syntax:
    content: esriCSPaused = 1
    return:
      type: ESRI.ArcGIS.Server.esriConfigurationStatus
- uid: ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSStopped
  commentId: F:ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSStopped
  id: esriCSStopped
  parent: ESRI.ArcGIS.Server.esriConfigurationStatus
  langs:
  - csharp
  - vb
  name: esriCSStopped
  nameWithType: esriConfigurationStatus.esriCSStopped
  fullName: ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSStopped
  type: Field
  assemblies:
  - ESRI.Server.Server
  namespace: ESRI.ArcGIS.Server
  summary: '2: The server object configuration is stopped.'
  example: []
  syntax:
    content: esriCSStopped = 2
    return:
      type: ESRI.ArcGIS.Server.esriConfigurationStatus
- uid: ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSStarting
  commentId: F:ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSStarting
  id: esriCSStarting
  parent: ESRI.ArcGIS.Server.esriConfigurationStatus
  langs:
  - csharp
  - vb
  name: esriCSStarting
  nameWithType: esriConfigurationStatus.esriCSStarting
  fullName: ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSStarting
  type: Field
  assemblies:
  - ESRI.Server.Server
  namespace: ESRI.ArcGIS.Server
  summary: '3: The server object configuration is starting.'
  example: []
  syntax:
    content: esriCSStarting = 3
    return:
      type: ESRI.ArcGIS.Server.esriConfigurationStatus
- uid: ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSStopping
  commentId: F:ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSStopping
  id: esriCSStopping
  parent: ESRI.ArcGIS.Server.esriConfigurationStatus
  langs:
  - csharp
  - vb
  name: esriCSStopping
  nameWithType: esriConfigurationStatus.esriCSStopping
  fullName: ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSStopping
  type: Field
  assemblies:
  - ESRI.Server.Server
  namespace: ESRI.ArcGIS.Server
  summary: '4: The server object configuration is stopping.'
  example: []
  syntax:
    content: esriCSStopping = 4
    return:
      type: ESRI.ArcGIS.Server.esriConfigurationStatus
- uid: ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSDeleted
  commentId: F:ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSDeleted
  id: esriCSDeleted
  parent: ESRI.ArcGIS.Server.esriConfigurationStatus
  langs:
  - csharp
  - vb
  name: esriCSDeleted
  nameWithType: esriConfigurationStatus.esriCSDeleted
  fullName: ESRI.ArcGIS.Server.esriConfigurationStatus.esriCSDeleted
  type: Field
  assemblies:
  - ESRI.Server.Server
  namespace: ESRI.ArcGIS.Server
  summary: '5: The server object configuration being deleted.'
  example: []
  syntax:
    content: esriCSDeleted = 5
    return:
      type: ESRI.ArcGIS.Server.esriConfigurationStatus
references:
- uid: ESRI.ArcGIS.Server
  commentId: N:ESRI.ArcGIS.Server
  isExternal: true
  href: ESRI.html
  name: ESRI.ArcGIS.Server
  nameWithType: ESRI.ArcGIS.Server
  fullName: ESRI.ArcGIS.Server
  spec.csharp:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.Server
    name: Server
    isExternal: true
    href: ESRI.ArcGIS.Server.html
  spec.vb:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.Server
    name: Server
    isExternal: true
    href: ESRI.ArcGIS.Server.html
- uid: ESRI.ArcGIS.Server.esriConfigurationStatus
  commentId: T:ESRI.ArcGIS.Server.esriConfigurationStatus
  parent: ESRI.ArcGIS.Server
  isExternal: true
  href: ESRI.ArcGIS.Server.esriConfigurationStatus.html
  name: esriConfigurationStatus
  nameWithType: esriConfigurationStatus
  fullName: ESRI.ArcGIS.Server.esriConfigurationStatus
