### YamlMime:ManagedReference
items:
- uid: ESRI.ArcGIS.DatasourcesRaster.UniqueValues
  commentId: T:ESRI.ArcGIS.DatasourcesRaster.UniqueValues
  id: UniqueValues
  parent: ESRI.ArcGIS.DatasourcesRaster
  children: []
  langs:
  - csharp
  - vb
  name: UniqueValues
  nameWithType: UniqueValues
  fullName: ESRI.ArcGIS.DatasourcesRaster.UniqueValues
  type: Interface
  assemblies:
  - ESRI.Server.DatasourcesRaster
  namespace: ESRI.ArcGIS.DatasourcesRaster
  summary: A raster unique value class.
  example: []
  syntax:
    content: >-
      [Guid("B2768AB2-E583-4CCF-831D-36237C2F520A")]

      public interface UniqueValues : IUniqueValues
    content.vb: >-
      <Guid("B2768AB2-E583-4CCF-831D-36237C2F520A")>

      Public Interface UniqueValues Inherits IUniqueValues
  derivedClasses:
  - ESRI.ArcGIS.DatasourcesRaster.UniqueValuesClass
  inheritedMembers:
  - ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Lookup(System.Int32)
  - ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Add(System.Int32,System.Int32)
  - ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Delete(System.Int32)
  - ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Empty
  - ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.GetHistogram(System.Object@,System.Object@)
  - ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.UniqueValue(System.Int32)
  - ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.UniqueCount(System.Int32)
  - ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Count
  - ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Min
  - ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Max
  attributes:
  - type: System.Runtime.InteropServices.GuidAttribute
    ctor: System.Runtime.InteropServices.GuidAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: B2768AB2-E583-4CCF-831D-36237C2F520A
references:
- uid: ESRI.ArcGIS.DatasourcesRaster
  commentId: N:ESRI.ArcGIS.DatasourcesRaster
  isExternal: true
  href: ESRI.html
  name: ESRI.ArcGIS.DatasourcesRaster
  nameWithType: ESRI.ArcGIS.DatasourcesRaster
  fullName: ESRI.ArcGIS.DatasourcesRaster
  spec.csharp:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.DatasourcesRaster
    name: DatasourcesRaster
    isExternal: true
    href: ESRI.ArcGIS.DatasourcesRaster.html
  spec.vb:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.DatasourcesRaster
    name: DatasourcesRaster
    isExternal: true
    href: ESRI.ArcGIS.DatasourcesRaster.html
- uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Lookup(System.Int32)
  commentId: M:ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Lookup(System.Int32)
  parent: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues
  isExternal: true
  href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_Lookup_System_Int32_
  name: Lookup(int)
  nameWithType: IUniqueValues.Lookup(int)
  fullName: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Lookup(int)
  nameWithType.vb: IUniqueValues.Lookup(Integer)
  fullName.vb: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Lookup(Integer)
  name.vb: Lookup(Integer)
  spec.csharp:
  - uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Lookup(System.Int32)
    name: Lookup
    isExternal: true
    href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_Lookup_System_Int32_
  - name: (
  - uid: System.Int32
    name: int
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: )
  spec.vb:
  - uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Lookup(System.Int32)
    name: Lookup
    isExternal: true
    href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_Lookup_System_Int32_
  - name: (
  - uid: System.Int32
    name: Integer
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: )
- uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Add(System.Int32,System.Int32)
  commentId: M:ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Add(System.Int32,System.Int32)
  parent: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues
  isExternal: true
  href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_Add_System_Int32_System_Int32_
  name: Add(int, int)
  nameWithType: IUniqueValues.Add(int, int)
  fullName: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Add(int, int)
  nameWithType.vb: IUniqueValues.Add(Integer, Integer)
  fullName.vb: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Add(Integer, Integer)
  name.vb: Add(Integer, Integer)
  spec.csharp:
  - uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Add(System.Int32,System.Int32)
    name: Add
    isExternal: true
    href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_Add_System_Int32_System_Int32_
  - name: (
  - uid: System.Int32
    name: int
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: ','
  - name: " "
  - uid: System.Int32
    name: int
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: )
  spec.vb:
  - uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Add(System.Int32,System.Int32)
    name: Add
    isExternal: true
    href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_Add_System_Int32_System_Int32_
  - name: (
  - uid: System.Int32
    name: Integer
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: ','
  - name: " "
  - uid: System.Int32
    name: Integer
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: )
- uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Delete(System.Int32)
  commentId: M:ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Delete(System.Int32)
  parent: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues
  isExternal: true
  href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_Delete_System_Int32_
  name: Delete(int)
  nameWithType: IUniqueValues.Delete(int)
  fullName: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Delete(int)
  nameWithType.vb: IUniqueValues.Delete(Integer)
  fullName.vb: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Delete(Integer)
  name.vb: Delete(Integer)
  spec.csharp:
  - uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Delete(System.Int32)
    name: Delete
    isExternal: true
    href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_Delete_System_Int32_
  - name: (
  - uid: System.Int32
    name: int
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: )
  spec.vb:
  - uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Delete(System.Int32)
    name: Delete
    isExternal: true
    href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_Delete_System_Int32_
  - name: (
  - uid: System.Int32
    name: Integer
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: )
- uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Empty
  commentId: M:ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Empty
  parent: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues
  isExternal: true
  href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_Empty
  name: Empty()
  nameWithType: IUniqueValues.Empty()
  fullName: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Empty()
  spec.csharp:
  - uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Empty
    name: Empty
    isExternal: true
    href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_Empty
  - name: (
  - name: )
  spec.vb:
  - uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Empty
    name: Empty
    isExternal: true
    href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_Empty
  - name: (
  - name: )
- uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.GetHistogram(System.Object@,System.Object@)
  commentId: M:ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.GetHistogram(System.Object@,System.Object@)
  parent: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues
  isExternal: true
  href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_GetHistogram_System_Object__System_Object__
  name: GetHistogram(out object, out object)
  nameWithType: IUniqueValues.GetHistogram(out object, out object)
  fullName: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.GetHistogram(out object, out object)
  nameWithType.vb: IUniqueValues.GetHistogram(Object, Object)
  fullName.vb: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.GetHistogram(Object, Object)
  name.vb: GetHistogram(Object, Object)
  spec.csharp:
  - uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.GetHistogram(System.Object@,System.Object@)
    name: GetHistogram
    isExternal: true
    href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_GetHistogram_System_Object__System_Object__
  - name: (
  - name: out
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - name: out
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.GetHistogram(System.Object@,System.Object@)
    name: GetHistogram
    isExternal: true
    href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_GetHistogram_System_Object__System_Object__
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.UniqueValue(System.Int32)
  commentId: P:ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.UniqueValue(System.Int32)
  parent: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues
  isExternal: true
  href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_UniqueValue_System_Int32_
  name: UniqueValue[int]
  nameWithType: IUniqueValues.UniqueValue[int]
  fullName: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.UniqueValue[int]
  nameWithType.vb: IUniqueValues.UniqueValue(Integer)
  fullName.vb: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.UniqueValue(Integer)
  name.vb: UniqueValue(Integer)
  spec.csharp:
  - uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.UniqueValue(System.Int32)
    name: UniqueValue
    isExternal: true
    href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_UniqueValue_System_Int32_
  - name: '['
  - uid: System.Int32
    name: int
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: ']'
  spec.vb:
  - uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.UniqueValue(System.Int32)
    name: UniqueValue
    isExternal: true
    href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_UniqueValue_System_Int32_
  - name: (
  - uid: System.Int32
    name: Integer
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: )
- uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.UniqueCount(System.Int32)
  commentId: P:ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.UniqueCount(System.Int32)
  parent: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues
  isExternal: true
  href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_UniqueCount_System_Int32_
  name: UniqueCount[int]
  nameWithType: IUniqueValues.UniqueCount[int]
  fullName: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.UniqueCount[int]
  nameWithType.vb: IUniqueValues.UniqueCount(Integer)
  fullName.vb: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.UniqueCount(Integer)
  name.vb: UniqueCount(Integer)
  spec.csharp:
  - uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.UniqueCount(System.Int32)
    name: UniqueCount
    isExternal: true
    href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_UniqueCount_System_Int32_
  - name: '['
  - uid: System.Int32
    name: int
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: ']'
  spec.vb:
  - uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.UniqueCount(System.Int32)
    name: UniqueCount
    isExternal: true
    href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_UniqueCount_System_Int32_
  - name: (
  - uid: System.Int32
    name: Integer
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: )
- uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Count
  commentId: P:ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Count
  parent: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues
  isExternal: true
  href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_Count
  name: Count
  nameWithType: IUniqueValues.Count
  fullName: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Count
- uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Min
  commentId: P:ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Min
  parent: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues
  isExternal: true
  href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_Min
  name: Min
  nameWithType: IUniqueValues.Min
  fullName: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Min
- uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Max
  commentId: P:ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Max
  parent: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues
  isExternal: true
  href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueValues_Max
  name: Max
  nameWithType: IUniqueValues.Max
  fullName: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.Max
- uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues
  commentId: T:ESRI.ArcGIS.DatasourcesRaster.IUniqueValues
  parent: ESRI.ArcGIS.DatasourcesRaster
  isExternal: true
  href: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues.html
  name: IUniqueValues
  nameWithType: IUniqueValues
  fullName: ESRI.ArcGIS.DatasourcesRaster.IUniqueValues
