### YamlMime:ManagedReference
items:
- uid: ESRI.ArcGIS.Geodatabase.UNTraceConfiguration
  commentId: T:ESRI.ArcGIS.Geodatabase.UNTraceConfiguration
  id: UNTraceConfiguration
  parent: ESRI.ArcGIS.Geodatabase
  children: []
  langs:
  - csharp
  - vb
  name: UNTraceConfiguration
  nameWithType: UNTraceConfiguration
  fullName: ESRI.ArcGIS.Geodatabase.UNTraceConfiguration
  type: Interface
  assemblies:
  - ESRI.Server.Geodatabase
  namespace: ESRI.ArcGIS.Geodatabase
  summary: Utility Network Trace Configuration.
  example: []
  syntax:
    content: >-
      [Guid("EA62BF80-86F4-499A-B9E7-B9735A33840A")]

      public interface UNTraceConfiguration : IUNTraceConfiguration
    content.vb: >-
      <Guid("EA62BF80-86F4-499A-B9E7-B9735A33840A")>

      Public Interface UNTraceConfiguration Inherits IUNTraceConfiguration
  derivedClasses:
  - ESRI.ArcGIS.Geodatabase.UNTraceConfigurationClass
  inheritedMembers:
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeContainers
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeContent
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeStructures
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeBarriers
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.ValidateConsistency
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeIsolated
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IgnoreBarriersAtStartingPoints
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeUpToFirstSpatialContainer
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.DomainNetworkName
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.TierName
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.TargetTierName
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.SubnetworkName
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.DiagramTemplateName
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.ShortestPathNetworkAttributeName
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.FilterBitsetNetworkAttributeName
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.TraversabilityScope
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.ConditionBarriers
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.FunctionBarriers
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.ArcadeExpressionBarrier
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.FilterBarriers
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.FilterFunctionBarriers
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.FilterScope
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.Functions
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.NearestNeighbor
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.OutputFilters
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.OutputConditions
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.Propagators
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.AllowIndeterminateFlow
  - ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.ValidateLocatability
  attributes:
  - type: System.Runtime.InteropServices.GuidAttribute
    ctor: System.Runtime.InteropServices.GuidAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: EA62BF80-86F4-499A-B9E7-B9735A33840A
references:
- uid: ESRI.ArcGIS.Geodatabase
  commentId: N:ESRI.ArcGIS.Geodatabase
  isExternal: true
  href: ESRI.html
  name: ESRI.ArcGIS.Geodatabase
  nameWithType: ESRI.ArcGIS.Geodatabase
  fullName: ESRI.ArcGIS.Geodatabase
  spec.csharp:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.Geodatabase
    name: Geodatabase
    isExternal: true
    href: ESRI.ArcGIS.Geodatabase.html
  spec.vb:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.Geodatabase
    name: Geodatabase
    isExternal: true
    href: ESRI.ArcGIS.Geodatabase.html
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeContainers
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeContainers
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_IncludeContainers
  name: IncludeContainers
  nameWithType: IUNTraceConfiguration.IncludeContainers
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeContainers
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeContent
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeContent
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_IncludeContent
  name: IncludeContent
  nameWithType: IUNTraceConfiguration.IncludeContent
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeContent
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeStructures
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeStructures
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_IncludeStructures
  name: IncludeStructures
  nameWithType: IUNTraceConfiguration.IncludeStructures
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeStructures
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeBarriers
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeBarriers
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_IncludeBarriers
  name: IncludeBarriers
  nameWithType: IUNTraceConfiguration.IncludeBarriers
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeBarriers
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.ValidateConsistency
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.ValidateConsistency
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_ValidateConsistency
  name: ValidateConsistency
  nameWithType: IUNTraceConfiguration.ValidateConsistency
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.ValidateConsistency
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeIsolated
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeIsolated
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_IncludeIsolated
  name: IncludeIsolated
  nameWithType: IUNTraceConfiguration.IncludeIsolated
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeIsolated
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IgnoreBarriersAtStartingPoints
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IgnoreBarriersAtStartingPoints
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_IgnoreBarriersAtStartingPoints
  name: IgnoreBarriersAtStartingPoints
  nameWithType: IUNTraceConfiguration.IgnoreBarriersAtStartingPoints
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IgnoreBarriersAtStartingPoints
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeUpToFirstSpatialContainer
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeUpToFirstSpatialContainer
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_IncludeUpToFirstSpatialContainer
  name: IncludeUpToFirstSpatialContainer
  nameWithType: IUNTraceConfiguration.IncludeUpToFirstSpatialContainer
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.IncludeUpToFirstSpatialContainer
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.DomainNetworkName
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.DomainNetworkName
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_DomainNetworkName
  name: DomainNetworkName
  nameWithType: IUNTraceConfiguration.DomainNetworkName
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.DomainNetworkName
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.TierName
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.TierName
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_TierName
  name: TierName
  nameWithType: IUNTraceConfiguration.TierName
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.TierName
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.TargetTierName
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.TargetTierName
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_TargetTierName
  name: TargetTierName
  nameWithType: IUNTraceConfiguration.TargetTierName
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.TargetTierName
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.SubnetworkName
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.SubnetworkName
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_SubnetworkName
  name: SubnetworkName
  nameWithType: IUNTraceConfiguration.SubnetworkName
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.SubnetworkName
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.DiagramTemplateName
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.DiagramTemplateName
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_DiagramTemplateName
  name: DiagramTemplateName
  nameWithType: IUNTraceConfiguration.DiagramTemplateName
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.DiagramTemplateName
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.ShortestPathNetworkAttributeName
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.ShortestPathNetworkAttributeName
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_ShortestPathNetworkAttributeName
  name: ShortestPathNetworkAttributeName
  nameWithType: IUNTraceConfiguration.ShortestPathNetworkAttributeName
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.ShortestPathNetworkAttributeName
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.FilterBitsetNetworkAttributeName
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.FilterBitsetNetworkAttributeName
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_FilterBitsetNetworkAttributeName
  name: FilterBitsetNetworkAttributeName
  nameWithType: IUNTraceConfiguration.FilterBitsetNetworkAttributeName
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.FilterBitsetNetworkAttributeName
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.TraversabilityScope
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.TraversabilityScope
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_TraversabilityScope
  name: TraversabilityScope
  nameWithType: IUNTraceConfiguration.TraversabilityScope
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.TraversabilityScope
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.ConditionBarriers
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.ConditionBarriers
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_ConditionBarriers
  name: ConditionBarriers
  nameWithType: IUNTraceConfiguration.ConditionBarriers
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.ConditionBarriers
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.FunctionBarriers
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.FunctionBarriers
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_FunctionBarriers
  name: FunctionBarriers
  nameWithType: IUNTraceConfiguration.FunctionBarriers
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.FunctionBarriers
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.ArcadeExpressionBarrier
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.ArcadeExpressionBarrier
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_ArcadeExpressionBarrier
  name: ArcadeExpressionBarrier
  nameWithType: IUNTraceConfiguration.ArcadeExpressionBarrier
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.ArcadeExpressionBarrier
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.FilterBarriers
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.FilterBarriers
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_FilterBarriers
  name: FilterBarriers
  nameWithType: IUNTraceConfiguration.FilterBarriers
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.FilterBarriers
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.FilterFunctionBarriers
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.FilterFunctionBarriers
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_FilterFunctionBarriers
  name: FilterFunctionBarriers
  nameWithType: IUNTraceConfiguration.FilterFunctionBarriers
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.FilterFunctionBarriers
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.FilterScope
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.FilterScope
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_FilterScope
  name: FilterScope
  nameWithType: IUNTraceConfiguration.FilterScope
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.FilterScope
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.Functions
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.Functions
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_Functions
  name: Functions
  nameWithType: IUNTraceConfiguration.Functions
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.Functions
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.NearestNeighbor
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.NearestNeighbor
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_NearestNeighbor
  name: NearestNeighbor
  nameWithType: IUNTraceConfiguration.NearestNeighbor
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.NearestNeighbor
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.OutputFilters
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.OutputFilters
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_OutputFilters
  name: OutputFilters
  nameWithType: IUNTraceConfiguration.OutputFilters
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.OutputFilters
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.OutputConditions
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.OutputConditions
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_OutputConditions
  name: OutputConditions
  nameWithType: IUNTraceConfiguration.OutputConditions
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.OutputConditions
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.Propagators
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.Propagators
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_Propagators
  name: Propagators
  nameWithType: IUNTraceConfiguration.Propagators
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.Propagators
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.AllowIndeterminateFlow
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.AllowIndeterminateFlow
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_AllowIndeterminateFlow
  name: AllowIndeterminateFlow
  nameWithType: IUNTraceConfiguration.AllowIndeterminateFlow
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.AllowIndeterminateFlow
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.ValidateLocatability
  commentId: P:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.ValidateLocatability
  parent: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html#ESRI_ArcGIS_Geodatabase_IUNTraceConfiguration_ValidateLocatability
  name: ValidateLocatability
  nameWithType: IUNTraceConfiguration.ValidateLocatability
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.ValidateLocatability
- uid: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  commentId: T:ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
  parent: ESRI.ArcGIS.Geodatabase
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration.html
  name: IUNTraceConfiguration
  nameWithType: IUNTraceConfiguration
  fullName: ESRI.ArcGIS.Geodatabase.IUNTraceConfiguration
