### YamlMime:ManagedReference
items:
- uid: ESRI.ArcGIS.Geodatabase.IWorkspaceConfiguration
  commentId: T:ESRI.ArcGIS.Geodatabase.IWorkspaceConfiguration
  id: IWorkspaceConfiguration
  parent: ESRI.ArcGIS.Geodatabase
  children:
  - ESRI.ArcGIS.Geodatabase.IWorkspaceConfiguration.ConfigurationKeywords
  langs:
  - csharp
  - vb
  name: IWorkspaceConfiguration
  nameWithType: IWorkspaceConfiguration
  fullName: ESRI.ArcGIS.Geodatabase.IWorkspaceConfiguration
  type: Interface
  assemblies:
  - ESRI.Server.Geodatabase
  namespace: ESRI.ArcGIS.Geodatabase
  summary: Provides access to configuration keywords.
  example: []
  syntax:
    content: >-
      [Guid("9E8F5C35-7888-4DF9-862C-9DD74EFF9062")]

      [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]

      public interface IWorkspaceConfiguration
    content.vb: >-
      <Guid("9E8F5C35-7888-4DF9-862C-9DD74EFF9062")>

      <InterfaceType(ComInterfaceType.InterfaceIsIUnknown)>

      Public Interface IWorkspaceConfiguration
  derivedClasses:
  - ESRI.ArcGIS.DatasourcesGDB.SqlWorkspaceClass
  - ESRI.ArcGIS.Geodatabase.WorkspaceClass
  attributes:
  - type: System.Runtime.InteropServices.GuidAttribute
    ctor: System.Runtime.InteropServices.GuidAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: 9E8F5C35-7888-4DF9-862C-9DD74EFF9062
  - type: System.Runtime.InteropServices.InterfaceTypeAttribute
    ctor: System.Runtime.InteropServices.InterfaceTypeAttribute.#ctor(System.Runtime.InteropServices.ComInterfaceType)
    arguments:
    - type: System.Runtime.InteropServices.ComInterfaceType
      value: 1
- uid: ESRI.ArcGIS.Geodatabase.IWorkspaceConfiguration.ConfigurationKeywords
  commentId: P:ESRI.ArcGIS.Geodatabase.IWorkspaceConfiguration.ConfigurationKeywords
  id: ConfigurationKeywords
  parent: ESRI.ArcGIS.Geodatabase.IWorkspaceConfiguration
  langs:
  - csharp
  - vb
  name: ConfigurationKeywords
  nameWithType: IWorkspaceConfiguration.ConfigurationKeywords
  fullName: ESRI.ArcGIS.Geodatabase.IWorkspaceConfiguration.ConfigurationKeywords
  type: Property
  assemblies:
  - ESRI.Server.Geodatabase
  namespace: ESRI.ArcGIS.Geodatabase
  summary: The available configuration keywords.
  example:
  - >-
    <codeTitle>Sample Snippet</codeTitle>

    <pre><code class="lang-csharp"></code></pre>
  syntax:
    content: IEnumConfigurationKeyword ConfigurationKeywords { get; }
    parameters: []
    return:
      type: ESRI.ArcGIS.Geodatabase.IEnumConfigurationKeyword
    content.vb: ReadOnly Property ConfigurationKeywords As IEnumConfigurationKeyword
  overload: ESRI.ArcGIS.Geodatabase.IWorkspaceConfiguration.ConfigurationKeywords*
references:
- uid: ESRI.ArcGIS.Geodatabase
  commentId: N:ESRI.ArcGIS.Geodatabase
  isExternal: true
  href: ESRI.html
  name: ESRI.ArcGIS.Geodatabase
  nameWithType: ESRI.ArcGIS.Geodatabase
  fullName: ESRI.ArcGIS.Geodatabase
  spec.csharp:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.Geodatabase
    name: Geodatabase
    isExternal: true
    href: ESRI.ArcGIS.Geodatabase.html
  spec.vb:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.Geodatabase
    name: Geodatabase
    isExternal: true
    href: ESRI.ArcGIS.Geodatabase.html
- uid: ESRI.ArcGIS.Geodatabase.IWorkspaceConfiguration.ConfigurationKeywords*
  commentId: Overload:ESRI.ArcGIS.Geodatabase.IWorkspaceConfiguration.ConfigurationKeywords
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IWorkspaceConfiguration.html#ESRI_ArcGIS_Geodatabase_IWorkspaceConfiguration_ConfigurationKeywords
  name: ConfigurationKeywords
  nameWithType: IWorkspaceConfiguration.ConfigurationKeywords
  fullName: ESRI.ArcGIS.Geodatabase.IWorkspaceConfiguration.ConfigurationKeywords
- uid: ESRI.ArcGIS.Geodatabase.IEnumConfigurationKeyword
  commentId: T:ESRI.ArcGIS.Geodatabase.IEnumConfigurationKeyword
  parent: ESRI.ArcGIS.Geodatabase
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IEnumConfigurationKeyword.html
  name: IEnumConfigurationKeyword
  nameWithType: IEnumConfigurationKeyword
  fullName: ESRI.ArcGIS.Geodatabase.IEnumConfigurationKeyword
