### YamlMime:ManagedReference
items:
- uid: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath
  commentId: T:ESRI.ArcGIS.Geodatabase.IValidConfigurationPath
  id: IValidConfigurationPath
  parent: ESRI.ArcGIS.Geodatabase
  children:
  - ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.Description
  - ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.ID
  - ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.Name
  - ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.TerminalPaths
  langs:
  - csharp
  - vb
  name: IValidConfigurationPath
  nameWithType: IValidConfigurationPath
  fullName: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath
  type: Interface
  assemblies:
  - ESRI.Server.Geodatabase
  namespace: ESRI.ArcGIS.Geodatabase
  summary: Provides access to members that specify the properties of a valid utility network terminal configuration path.
  example: []
  syntax:
    content: >-
      [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]

      [Guid("DCA203F8-C428-49D4-813E-09A2431B6F2F")]

      public interface IValidConfigurationPath
    content.vb: >-
      <InterfaceType(ComInterfaceType.InterfaceIsIUnknown)>

      <Guid("DCA203F8-C428-49D4-813E-09A2431B6F2F")>

      Public Interface IValidConfigurationPath
  attributes:
  - type: System.Runtime.InteropServices.InterfaceTypeAttribute
    ctor: System.Runtime.InteropServices.InterfaceTypeAttribute.#ctor(System.Runtime.InteropServices.ComInterfaceType)
    arguments:
    - type: System.Runtime.InteropServices.ComInterfaceType
      value: 1
  - type: System.Runtime.InteropServices.GuidAttribute
    ctor: System.Runtime.InteropServices.GuidAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: DCA203F8-C428-49D4-813E-09A2431B6F2F
- uid: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.ID
  commentId: P:ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.ID
  id: ID
  parent: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath
  langs:
  - csharp
  - vb
  name: ID
  nameWithType: IValidConfigurationPath.ID
  fullName: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.ID
  type: Property
  assemblies:
  - ESRI.Server.Geodatabase
  namespace: ESRI.ArcGIS.Geodatabase
  summary: Returns the ID.
  example:
  - >-
    <codeTitle>Sample Snippet</codeTitle>

    <pre><code class="lang-csharp"></code></pre>
  syntax:
    content: int ID { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: ReadOnly Property ID As Integer
  overload: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.ID*
- uid: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.Name
  commentId: P:ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.Name
  id: Name
  parent: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: IValidConfigurationPath.Name
  fullName: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.Name
  type: Property
  assemblies:
  - ESRI.Server.Geodatabase
  namespace: ESRI.ArcGIS.Geodatabase
  summary: Returns the name.
  example:
  - >-
    <codeTitle>Sample Snippet</codeTitle>

    <pre><code class="lang-csharp"></code></pre>
  syntax:
    content: string Name { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property Name As String
  overload: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.Name*
- uid: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.Description
  commentId: P:ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.Description
  id: Description
  parent: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath
  langs:
  - csharp
  - vb
  name: Description
  nameWithType: IValidConfigurationPath.Description
  fullName: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.Description
  type: Property
  assemblies:
  - ESRI.Server.Geodatabase
  namespace: ESRI.ArcGIS.Geodatabase
  summary: Returns the description.
  example:
  - >-
    <codeTitle>Sample Snippet</codeTitle>

    <pre><code class="lang-csharp"></code></pre>
  syntax:
    content: string Description { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property Description As String
  overload: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.Description*
- uid: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.TerminalPaths
  commentId: P:ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.TerminalPaths
  id: TerminalPaths
  parent: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath
  langs:
  - csharp
  - vb
  name: TerminalPaths
  nameWithType: IValidConfigurationPath.TerminalPaths
  fullName: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.TerminalPaths
  type: Property
  assemblies:
  - ESRI.Server.Geodatabase
  namespace: ESRI.ArcGIS.Geodatabase
  summary: Returns the terminal paths.
  example:
  - >-
    <codeTitle>Sample Snippet</codeTitle>

    <pre><code class="lang-csharp"></code></pre>
  syntax:
    content: IArray TerminalPaths { get; }
    parameters: []
    return:
      type: ESRI.ArcGIS.esriSystem.IArray
    content.vb: ReadOnly Property TerminalPaths As IArray
  overload: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.TerminalPaths*
references:
- uid: ESRI.ArcGIS.Geodatabase
  commentId: N:ESRI.ArcGIS.Geodatabase
  isExternal: true
  href: ESRI.html
  name: ESRI.ArcGIS.Geodatabase
  nameWithType: ESRI.ArcGIS.Geodatabase
  fullName: ESRI.ArcGIS.Geodatabase
  spec.csharp:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.Geodatabase
    name: Geodatabase
    isExternal: true
    href: ESRI.ArcGIS.Geodatabase.html
  spec.vb:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.Geodatabase
    name: Geodatabase
    isExternal: true
    href: ESRI.ArcGIS.Geodatabase.html
- uid: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.ID*
  commentId: Overload:ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.ID
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.html#ESRI_ArcGIS_Geodatabase_IValidConfigurationPath_ID
  name: ID
  nameWithType: IValidConfigurationPath.ID
  fullName: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.ID
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.Name*
  commentId: Overload:ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.Name
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.html#ESRI_ArcGIS_Geodatabase_IValidConfigurationPath_Name
  name: Name
  nameWithType: IValidConfigurationPath.Name
  fullName: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.Description*
  commentId: Overload:ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.Description
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.html#ESRI_ArcGIS_Geodatabase_IValidConfigurationPath_Description
  name: Description
  nameWithType: IValidConfigurationPath.Description
  fullName: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.Description
- uid: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.TerminalPaths*
  commentId: Overload:ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.TerminalPaths
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.html#ESRI_ArcGIS_Geodatabase_IValidConfigurationPath_TerminalPaths
  name: TerminalPaths
  nameWithType: IValidConfigurationPath.TerminalPaths
  fullName: ESRI.ArcGIS.Geodatabase.IValidConfigurationPath.TerminalPaths
- uid: ESRI.ArcGIS.esriSystem.IArray
  commentId: T:ESRI.ArcGIS.esriSystem.IArray
  parent: ESRI.ArcGIS.esriSystem
  isExternal: true
  href: ESRI.ArcGIS.esriSystem.IArray.html
  name: IArray
  nameWithType: IArray
  fullName: ESRI.ArcGIS.esriSystem.IArray
- uid: ESRI.ArcGIS.esriSystem
  commentId: N:ESRI.ArcGIS.esriSystem
  isExternal: true
  href: ESRI.html
  name: ESRI.ArcGIS.esriSystem
  nameWithType: ESRI.ArcGIS.esriSystem
  fullName: ESRI.ArcGIS.esriSystem
  spec.csharp:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.esriSystem
    name: esriSystem
    isExternal: true
    href: ESRI.ArcGIS.esriSystem.html
  spec.vb:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.esriSystem
    name: esriSystem
    isExternal: true
    href: ESRI.ArcGIS.esriSystem.html
