### YamlMime:ManagedReference
items:
- uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues
  commentId: T:ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues
  id: IUniqueStringValues
  parent: ESRI.ArcGIS.DatasourcesRaster
  children:
  - ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Add(System.String,System.Int32)
  - ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Delete(System.String)
  - ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Lookup(System.String)
  langs:
  - csharp
  - vb
  name: IUniqueStringValues
  nameWithType: IUniqueStringValues
  fullName: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues
  type: Interface
  assemblies:
  - ESRI.Server.DatasourcesRaster
  namespace: ESRI.ArcGIS.DatasourcesRaster
  summary: Provides access to members that controls unique string values.
  example: []
  syntax:
    content: >-
      [Guid("B39479E3-EC24-49CE-B268-556375700B8A")]

      [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]

      public interface IUniqueStringValues
    content.vb: >-
      <Guid("B39479E3-EC24-49CE-B268-556375700B8A")>

      <InterfaceType(ComInterfaceType.InterfaceIsIUnknown)>

      Public Interface IUniqueStringValues
  derivedClasses:
  - ESRI.ArcGIS.DatasourcesRaster.UniqueValuesClass
  attributes:
  - type: System.Runtime.InteropServices.GuidAttribute
    ctor: System.Runtime.InteropServices.GuidAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: B39479E3-EC24-49CE-B268-556375700B8A
  - type: System.Runtime.InteropServices.InterfaceTypeAttribute
    ctor: System.Runtime.InteropServices.InterfaceTypeAttribute.#ctor(System.Runtime.InteropServices.ComInterfaceType)
    arguments:
    - type: System.Runtime.InteropServices.ComInterfaceType
      value: 1
- uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Lookup(System.String)
  commentId: M:ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Lookup(System.String)
  id: Lookup(System.String)
  parent: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues
  langs:
  - csharp
  - vb
  name: Lookup(string)
  nameWithType: IUniqueStringValues.Lookup(string)
  fullName: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Lookup(string)
  type: Method
  assemblies:
  - ESRI.Server.DatasourcesRaster
  namespace: ESRI.ArcGIS.DatasourcesRaster
  summary: Looks up unique index of a given value.
  example:
  - >-
    <codeTitle>Sample Snippet</codeTitle>

    <pre><code class="lang-csharp"></code></pre>
  syntax:
    content: int Lookup(string Value)
    parameters:
    - id: Value
      type: System.String
    return:
      type: System.Int32
    content.vb: Function Lookup(Value As String) As Integer
  overload: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Lookup*
  nameWithType.vb: IUniqueStringValues.Lookup(String)
  fullName.vb: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Lookup(String)
  name.vb: Lookup(String)
- uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Add(System.String,System.Int32)
  commentId: M:ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Add(System.String,System.Int32)
  id: Add(System.String,System.Int32)
  parent: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues
  langs:
  - csharp
  - vb
  name: Add(string, int)
  nameWithType: IUniqueStringValues.Add(string, int)
  fullName: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Add(string, int)
  type: Method
  assemblies:
  - ESRI.Server.DatasourcesRaster
  namespace: ESRI.ArcGIS.DatasourcesRaster
  summary: Adds a value if necessary and returns its value ID.
  example:
  - >-
    <codeTitle>Sample Snippet</codeTitle>

    <pre><code class="lang-csharp"></code></pre>
  syntax:
    content: int Add(string Value, int Count)
    parameters:
    - id: Value
      type: System.String
    - id: Count
      type: System.Int32
    return:
      type: System.Int32
    content.vb: Function Add(Value As String, Count As Integer) As Integer
  overload: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Add*
  nameWithType.vb: IUniqueStringValues.Add(String, Integer)
  fullName.vb: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Add(String, Integer)
  name.vb: Add(String, Integer)
- uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Delete(System.String)
  commentId: M:ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Delete(System.String)
  id: Delete(System.String)
  parent: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues
  langs:
  - csharp
  - vb
  name: Delete(string)
  nameWithType: IUniqueStringValues.Delete(string)
  fullName: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Delete(string)
  type: Method
  assemblies:
  - ESRI.Server.DatasourcesRaster
  namespace: ESRI.ArcGIS.DatasourcesRaster
  summary: Deletes a value.
  example:
  - >-
    <codeTitle>Sample Snippet</codeTitle>

    <pre><code class="lang-csharp"></code></pre>
  syntax:
    content: void Delete(string Value)
    parameters:
    - id: Value
      type: System.String
    content.vb: Sub Delete(Value As String)
  overload: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Delete*
  nameWithType.vb: IUniqueStringValues.Delete(String)
  fullName.vb: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Delete(String)
  name.vb: Delete(String)
references:
- uid: ESRI.ArcGIS.DatasourcesRaster
  commentId: N:ESRI.ArcGIS.DatasourcesRaster
  isExternal: true
  href: ESRI.html
  name: ESRI.ArcGIS.DatasourcesRaster
  nameWithType: ESRI.ArcGIS.DatasourcesRaster
  fullName: ESRI.ArcGIS.DatasourcesRaster
  spec.csharp:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.DatasourcesRaster
    name: DatasourcesRaster
    isExternal: true
    href: ESRI.ArcGIS.DatasourcesRaster.html
  spec.vb:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.DatasourcesRaster
    name: DatasourcesRaster
    isExternal: true
    href: ESRI.ArcGIS.DatasourcesRaster.html
- uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Lookup*
  commentId: Overload:ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Lookup
  isExternal: true
  href: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueStringValues_Lookup_System_String_
  name: Lookup
  nameWithType: IUniqueStringValues.Lookup
  fullName: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Lookup
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Add*
  commentId: Overload:ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Add
  isExternal: true
  href: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueStringValues_Add_System_String_System_Int32_
  name: Add
  nameWithType: IUniqueStringValues.Add
  fullName: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Add
- uid: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Delete*
  commentId: Overload:ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Delete
  isExternal: true
  href: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.html#ESRI_ArcGIS_DatasourcesRaster_IUniqueStringValues_Delete_System_String_
  name: Delete
  nameWithType: IUniqueStringValues.Delete
  fullName: ESRI.ArcGIS.DatasourcesRaster.IUniqueStringValues.Delete
