### YamlMime:ManagedReference
items:
- uid: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus
  commentId: T:ESRI.ArcGIS.Server.IServerObjectConfigurationStatus
  id: IServerObjectConfigurationStatus
  parent: ESRI.ArcGIS.Server
  children:
  - ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.InstanceCount
  - ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.InstanceInUseCount
  - ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.Status
  langs:
  - csharp
  - vb
  name: IServerObjectConfigurationStatus
  nameWithType: IServerObjectConfigurationStatus
  fullName: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus
  type: Interface
  assemblies:
  - ESRI.Server.Server
  namespace: ESRI.ArcGIS.Server
  summary: Provides access to properties of a server object configuration's status to administrators.
  example: []
  syntax:
    content: >-
      [Guid("096B178F-2576-4AEF-9CFA-8107D529BBFF")]

      [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]

      public interface IServerObjectConfigurationStatus
    content.vb: >-
      <Guid("096B178F-2576-4AEF-9CFA-8107D529BBFF")>

      <InterfaceType(ComInterfaceType.InterfaceIsIUnknown)>

      Public Interface IServerObjectConfigurationStatus
  attributes:
  - type: System.Runtime.InteropServices.GuidAttribute
    ctor: System.Runtime.InteropServices.GuidAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: 096B178F-2576-4AEF-9CFA-8107D529BBFF
  - type: System.Runtime.InteropServices.InterfaceTypeAttribute
    ctor: System.Runtime.InteropServices.InterfaceTypeAttribute.#ctor(System.Runtime.InteropServices.ComInterfaceType)
    arguments:
    - type: System.Runtime.InteropServices.ComInterfaceType
      value: 1
- uid: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.InstanceCount
  commentId: P:ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.InstanceCount
  id: InstanceCount
  parent: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus
  langs:
  - csharp
  - vb
  name: InstanceCount
  nameWithType: IServerObjectConfigurationStatus.InstanceCount
  fullName: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.InstanceCount
  type: Property
  assemblies:
  - ESRI.Server.Server
  namespace: ESRI.ArcGIS.Server
  summary: Number of instances of server objects for a particular configuration that are currently running in the GIS server.
  example:
  - >-
    <codeTitle>Sample Snippet</codeTitle>

    <pre><code class="lang-csharp"></code></pre>
  syntax:
    content: int InstanceCount { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: ReadOnly Property InstanceCount As Integer
  overload: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.InstanceCount*
- uid: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.InstanceInUseCount
  commentId: P:ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.InstanceInUseCount
  id: InstanceInUseCount
  parent: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus
  langs:
  - csharp
  - vb
  name: InstanceInUseCount
  nameWithType: IServerObjectConfigurationStatus.InstanceInUseCount
  fullName: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.InstanceInUseCount
  type: Property
  assemblies:
  - ESRI.Server.Server
  namespace: ESRI.ArcGIS.Server
  summary: Number of running instances of server objects for a particular configuration that are in currently use by clients of the GIS server.
  example:
  - >-
    <codeTitle>Sample Snippet</codeTitle>

    <pre><code class="lang-csharp"></code></pre>
  syntax:
    content: int InstanceInUseCount { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: ReadOnly Property InstanceInUseCount As Integer
  overload: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.InstanceInUseCount*
- uid: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.Status
  commentId: P:ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.Status
  id: Status
  parent: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus
  langs:
  - csharp
  - vb
  name: Status
  nameWithType: IServerObjectConfigurationStatus.Status
  fullName: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.Status
  type: Property
  assemblies:
  - ESRI.Server.Server
  namespace: ESRI.ArcGIS.Server
  summary: Status of the server object configuration. This status indicates whether the server object configuration is started, stopped, paused, etc.
  example:
  - >-
    <codeTitle>Sample Snippet</codeTitle>

    <pre><code class="lang-csharp"></code></pre>
  syntax:
    content: esriConfigurationStatus Status { get; }
    parameters: []
    return:
      type: ESRI.ArcGIS.Server.esriConfigurationStatus
    content.vb: ReadOnly Property Status As esriConfigurationStatus
  overload: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.Status*
references:
- uid: ESRI.ArcGIS.Server
  commentId: N:ESRI.ArcGIS.Server
  isExternal: true
  href: ESRI.html
  name: ESRI.ArcGIS.Server
  nameWithType: ESRI.ArcGIS.Server
  fullName: ESRI.ArcGIS.Server
  spec.csharp:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.Server
    name: Server
    isExternal: true
    href: ESRI.ArcGIS.Server.html
  spec.vb:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.Server
    name: Server
    isExternal: true
    href: ESRI.ArcGIS.Server.html
- uid: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.InstanceCount*
  commentId: Overload:ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.InstanceCount
  isExternal: true
  href: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.html#ESRI_ArcGIS_Server_IServerObjectConfigurationStatus_InstanceCount
  name: InstanceCount
  nameWithType: IServerObjectConfigurationStatus.InstanceCount
  fullName: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.InstanceCount
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.InstanceInUseCount*
  commentId: Overload:ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.InstanceInUseCount
  isExternal: true
  href: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.html#ESRI_ArcGIS_Server_IServerObjectConfigurationStatus_InstanceInUseCount
  name: InstanceInUseCount
  nameWithType: IServerObjectConfigurationStatus.InstanceInUseCount
  fullName: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.InstanceInUseCount
- uid: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.Status*
  commentId: Overload:ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.Status
  isExternal: true
  href: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.html#ESRI_ArcGIS_Server_IServerObjectConfigurationStatus_Status
  name: Status
  nameWithType: IServerObjectConfigurationStatus.Status
  fullName: ESRI.ArcGIS.Server.IServerObjectConfigurationStatus.Status
- uid: ESRI.ArcGIS.Server.esriConfigurationStatus
  commentId: T:ESRI.ArcGIS.Server.esriConfigurationStatus
  parent: ESRI.ArcGIS.Server
  isExternal: true
  href: ESRI.ArcGIS.Server.esriConfigurationStatus.html
  name: esriConfigurationStatus
  nameWithType: esriConfigurationStatus
  fullName: ESRI.ArcGIS.Server.esriConfigurationStatus
