### YamlMime:ManagedReference
items:
- uid: ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass
  commentId: T:ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass
  id: ConfigurationParameterClass
  parent: ESRI.ArcGIS.Geodatabase
  children:
  - ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass.ConfigurationString
  - ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass.Name
  langs:
  - csharp
  - vb
  name: ConfigurationParameterClass
  nameWithType: ConfigurationParameterClass
  fullName: ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass
  type: Class
  assemblies:
  - ESRI.Server.Geodatabase
  namespace: ESRI.ArcGIS.Geodatabase
  syntax:
    content: >-
      [ClassInterface(ClassInterfaceType.None)]

      [Guid("FBF57162-A05D-11D4-A64C-0008C711C8C1")]

      public class ConfigurationParameterClass : ConfigurationParameter, IConfigurationParameter
    content.vb: >-
      <ClassInterface(ClassInterfaceType.None)>

      <Guid("FBF57162-A05D-11D4-A64C-0008C711C8C1")>

      Public Class ConfigurationParameterClass Implements ConfigurationParameter, IConfigurationParameter
  inheritance:
  - System.Object
  implements:
  - ESRI.ArcGIS.Geodatabase.ConfigurationParameter
  - ESRI.ArcGIS.Geodatabase.IConfigurationParameter
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  attributes:
  - type: System.Runtime.InteropServices.ClassInterfaceAttribute
    ctor: System.Runtime.InteropServices.ClassInterfaceAttribute.#ctor(System.Runtime.InteropServices.ClassInterfaceType)
    arguments:
    - type: System.Runtime.InteropServices.ClassInterfaceType
      value: 0
  - type: System.Runtime.InteropServices.GuidAttribute
    ctor: System.Runtime.InteropServices.GuidAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: FBF57162-A05D-11D4-A64C-0008C711C8C1
- uid: ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass.Name
  commentId: P:ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass.Name
  id: Name
  isEii: true
  parent: ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: ConfigurationParameterClass.Name
  fullName: ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass.Name
  type: Property
  assemblies:
  - ESRI.Server.Geodatabase
  namespace: ESRI.ArcGIS.Geodatabase
  summary: The name of the parameter.
  example:
  - >-
    <codeTitle>Sample Snippet</codeTitle>

    <pre><code class="lang-csharp"></code></pre>
  syntax:
    content: virtual string Name { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Overridable Property Name As String
  overload: ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass.Name*
  implements:
  - ESRI.ArcGIS.Geodatabase.IConfigurationParameter.Name
- uid: ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass.ConfigurationString
  commentId: P:ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass.ConfigurationString
  id: ConfigurationString
  isEii: true
  parent: ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass
  langs:
  - csharp
  - vb
  name: ConfigurationString
  nameWithType: ConfigurationParameterClass.ConfigurationString
  fullName: ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass.ConfigurationString
  type: Property
  assemblies:
  - ESRI.Server.Geodatabase
  namespace: ESRI.ArcGIS.Geodatabase
  summary: The configuration string defined by the parameter.
  example:
  - >-
    <codeTitle>Sample Snippet</codeTitle>

    <pre><code class="lang-csharp"></code></pre>
  syntax:
    content: virtual string ConfigurationString { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Overridable Property ConfigurationString As String
  overload: ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass.ConfigurationString*
  implements:
  - ESRI.ArcGIS.Geodatabase.IConfigurationParameter.ConfigurationString
references:
- uid: ESRI.ArcGIS.Geodatabase
  commentId: N:ESRI.ArcGIS.Geodatabase
  isExternal: true
  href: ESRI.html
  name: ESRI.ArcGIS.Geodatabase
  nameWithType: ESRI.ArcGIS.Geodatabase
  fullName: ESRI.ArcGIS.Geodatabase
  spec.csharp:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.Geodatabase
    name: Geodatabase
    isExternal: true
    href: ESRI.ArcGIS.Geodatabase.html
  spec.vb:
  - uid: ESRI
    name: ESRI
    isExternal: true
    href: ESRI.html
  - name: .
  - uid: ESRI.ArcGIS
    name: ArcGIS
    isExternal: true
    href: ESRI.ArcGIS.html
  - name: .
  - uid: ESRI.ArcGIS.Geodatabase
    name: Geodatabase
    isExternal: true
    href: ESRI.ArcGIS.Geodatabase.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: ESRI.ArcGIS.Geodatabase.ConfigurationParameter
  commentId: T:ESRI.ArcGIS.Geodatabase.ConfigurationParameter
  parent: ESRI.ArcGIS.Geodatabase
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.ConfigurationParameter.html
  name: ConfigurationParameter
  nameWithType: ConfigurationParameter
  fullName: ESRI.ArcGIS.Geodatabase.ConfigurationParameter
- uid: ESRI.ArcGIS.Geodatabase.IConfigurationParameter
  commentId: T:ESRI.ArcGIS.Geodatabase.IConfigurationParameter
  parent: ESRI.ArcGIS.Geodatabase
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IConfigurationParameter.html
  name: IConfigurationParameter
  nameWithType: IConfigurationParameter
  fullName: ESRI.ArcGIS.Geodatabase.IConfigurationParameter
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass.Name*
  commentId: Overload:ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass.Name
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass.html#ESRI_ArcGIS_Geodatabase_ConfigurationParameterClass_Name
  name: Name
  nameWithType: ConfigurationParameterClass.Name
  fullName: ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass.Name
- uid: ESRI.ArcGIS.Geodatabase.IConfigurationParameter.Name
  commentId: P:ESRI.ArcGIS.Geodatabase.IConfigurationParameter.Name
  parent: ESRI.ArcGIS.Geodatabase.IConfigurationParameter
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IConfigurationParameter.html#ESRI_ArcGIS_Geodatabase_IConfigurationParameter_Name
  name: Name
  nameWithType: IConfigurationParameter.Name
  fullName: ESRI.ArcGIS.Geodatabase.IConfigurationParameter.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass.ConfigurationString*
  commentId: Overload:ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass.ConfigurationString
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass.html#ESRI_ArcGIS_Geodatabase_ConfigurationParameterClass_ConfigurationString
  name: ConfigurationString
  nameWithType: ConfigurationParameterClass.ConfigurationString
  fullName: ESRI.ArcGIS.Geodatabase.ConfigurationParameterClass.ConfigurationString
- uid: ESRI.ArcGIS.Geodatabase.IConfigurationParameter.ConfigurationString
  commentId: P:ESRI.ArcGIS.Geodatabase.IConfigurationParameter.ConfigurationString
  parent: ESRI.ArcGIS.Geodatabase.IConfigurationParameter
  isExternal: true
  href: ESRI.ArcGIS.Geodatabase.IConfigurationParameter.html#ESRI_ArcGIS_Geodatabase_IConfigurationParameter_ConfigurationString
  name: ConfigurationString
  nameWithType: IConfigurationParameter.ConfigurationString
  fullName: ESRI.ArcGIS.Geodatabase.IConfigurationParameter.ConfigurationString
